CHESSComputing/ChessAnalysisPipeline

async.py
The new module provides fully working example of asyncio processor, i.e. process tasks concurrently. We may use it as an example of build more complicated concurrent workflows.
=> Example of async IO processor

MLaaS/README.md, MLaaS/demo.sh, MLaaS/ktrain.py, MLaaS/mnist_img.py, MLaaS/tfaas_client.py
This PR contains full implementation of MLaaS workflow based on Keras python framework for ML training and TFaas for inference. Please refer to provided README.md for all technical details.
=> First draft of MLaaS example based on MNIST dataset

MLaaS/tfaas_client.py, inference/pipeline.yaml, processor.py, reader.py, test-data/config.yaml
This is proof-of-concept which includes the following components:
- BinaryFileReader to read raw images, e.g. png image
- TFaaSImageProcessor to process inference request
- inference directory with working configuration
- additional changes to tfaas_client code to work with python3
- fixes for test-data configuration
=> Inference producer

CHAP/TaskManager.py, CHAP/runner.py, CHAP/server.py
This PR contains proof-of-concept for autonomous server and CHAP pipeline. The server is based on [Flask](https://flask.palletsprojects.com/en/2.2.x/) HTTP framework. The server integrates CHAP into HTTP server such that clients can communicate with it via HTTP protocol.
For example, we can start the server as following:
```
flask --app server run
* Serving Flask app 'server'
* Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
* Running on http://127.0.0.1:5000
Press CTRL+C to quit
```
At this point it is ready to consume HTTP requests, and we'll provide one via the following command:
```
cat /tmp/chap.json
{
"pipeline": [{"common.PrintProcessor": {}}],
"input": 1
}
curl -X POST -H "Content-type: …
```
=> Support for autonomous server

CHAP/tomo/models.py, CHAP/tomo/processor.py, galaxy-tools/tomo/tomo_macros.xml
Also:
Updated galaxy-tools/tomo/tomo_macros.xml with CHAP v0.0.8 and
Zenodo citation info
=> style: Added/updated docstrings for tomo

CHAP/runner.py
This is first draft of possible changes we may need to support User processors. So far I'll leave code like this, but later we may organize it differently based on structure how we'll support user processors.
=> Add support for UserProcessor (part of CHAPaaS)

CHAP/common/models/map.py, CHAP/common/processor.py, CHAP/runner.py, CHAP/tomo/processor.py, CHAP/utils/scanparsers.py, examples/tomo/map_id3a.yaml, examples/tomo/map_id3b.yaml, examples/tomo/pipeline_id3a.yaml, examples/tomo/pipeline_id3b.yaml, examples/tomo/reduce_data_id3b.yaml
Preparation to implement new map reader concept
=> refactor: cleanup tomo and scanparser to use smb_pars and columns

CHAP/tomo/models.py, CHAP/tomo/processor.py
Also renamed x/y in the image fields to row/column, so that we can
reserve x,y,z for outputs in the physical lab frame
=> style: added units to tomo Nexus outputs

CHAP/tomo/processor.py
which affected selecting a ROI of the reconstructed data set
=> fix: fixed x,y,z order bugs in CHAP/tomo/processor.py

CHAP/tomo/models.py, CHAP/tomo/processor.py
Also refactored CHAP.tomo.processor._resize_reconstructed_data
=> fix: fixed bugs found in testing tomo test cases

CHAP/common/models/map.py, CHAP/utils/scanparsers.py
This can be used to set a path to the SMB par file different from the default one, in case it needs editing due to erroneous data.
=> feat: Added an optional 'par_file' field to class SpecScan

CHAP/common/reader.py, CHAP/tomo/models.py, CHAP/tomo/processor.py, CHAP/utils/general.py
Also:
- Fixed NXroot issue when the tomo input field are from MapReader.
- Added a center search over a given range option to find center axis
- Removed *_indices attrs from NXdata groups
- Improved speed when lazily reading NXfields at a bunch of occasions
- Fixed the logger for class Tomo
- Added a maximum number of entries in CHAP.utils.general.input_int/num_list
=> fix: overhauled the interactive tomo find center search routine

CHAP/edd/models.py, CHAP/edd/processor.py, CHAP/edd/utils.py
Add automated or manual peak finding to energy calibration
=> refactor: Eliminate max_energy_kev

CHAP/common/processor.py, CHAP/edd/reader.py, CHAP/giwaxs/processor.py, CHAP/runner.py, CHAP/utils/general.py
Also fixed a bug in CHAP/runner.py that causes an error when a processor has no arguments in the pipeline yaml file.
=> refactor: added list_to_string to simplify index lists inputs

CHAP/common/models/map.py, CHAP/edd/reader.py, CHAP/utils/fit.py, CHAP/utils/parfile.py
Only tested and updated for:
2023-3/id1a3/yeung-3714-b/v8-p3-10s-0deg
=> fix: make EDD backward compatible with older par files

CHAP/edd/environment.yml, CHAP/edd/processor.py, CHAP/giwaxs/environment.yml, CHAP/tomo/environment.yml
Also updated some CHAP environments
=> fix: error in detector name conversion

CHAP/edd/processor.py
Also set any negative data to zero after EDD baseline correction
=> fix: EDD animation axis scale and data normalization

CHAP/runner.py
by adding a CHAP command option --pipeline
=> add: allow sub pipeline selection in the pipeline config

CHAP/common/__init__.py, CHAP/common/processor.py, CHAP/edd/reader.py
Also fixed CHAP.edd.reader.UpdateNXdataReader to use the new UpdateNXvalueProcessor and thus return a list of points with nxpath, index and value.
=> add: CHAP.common.processor.UpdateNXvalueProcessor added

CHAP/edd/processor.py
Also refactored the raw data reading and mask/hkl selection
=> fix: Now (incrementatlly) updating the summed detector data

CHAP/edd/processor.py
Also added the missing baseline and mat prop bits
=> fix: fix errors in interative mode

CHAP/foxden/__init__.py, CHAP/foxden/processor.py, CHAP/foxden/reader.py, CHAP/foxden/writer.py
This PR adds implementation for FoxdenMetaDataWriter and FoxdenMetaDataProcessor. We can chain them along with Provenance ones as following:
```
config:
inputdir: .
outputdir: output # Change as desired
interactive: true # Change as desired
log_level: INFO
profile: false
pipeline:
- foxden.FoxdenMetaDataReader:
spec:
did: "/beamline=3a/btr=test-987-b/cycle=2024-3/sample_name=lup-20kev-1/test=child"
beam_energy: 312.462
url: "http://localhost:8300"
- foxden.FoxdenMetaDataProcessor:
url: "http://localhost:8300"
verbose: True
- foxden.FoxdenMetaDataWriter:
url: "http://localhost:8300"
verbose: True
- common.PrintProcessor: {}
- foxden.FoxdenMetaDataReader:
spec:
did: "/beamline=3a/btr=test-987-b/cycle=2024-3/sample_name=lup-20kev-1/test=child"
beam_energy: 312.462
url: …
```
=> Add implementation for FoxdenMetaDataWriter and FoxdenMetaDataProcessor

CHAP/common/utils.py, CHAP/foxden/__init__.py, CHAP/foxden/processor.py, CHAP/foxden/reader.py, CHAP/foxden/writer.py, examples/foxden/foxden_demo.yml
This PR provides further code-refactoring to support FOXDEN within CHAP. And, it provides new `FoxdenDoi Writer` class to perform publication of user's datasets within FOXDEN.
=> Additional changes to support FOXDEN within CHAP

CHAP/common/processor.py
=> add: Modified common.UnstructuredToStructuredProcessor to allow NXroot

CHAP/common/__init__.py, CHAP/common/map_utils.py, CHAP/common/nexus_utils.py, CHAP/common/processor.py, CHAP/common/reader.py, CHAP/common/writer.py, CHAP/saxswaxs/__init__.py, CHAP/saxswaxs/processor.py
Includes new PipelineItems for generic pieces of SAXS/WAXS workflow
Add thickness correction option
=> Merge updates to CHAP.common
